[2025-09-19T04:36:18.653+0000] {processor.py:161} INFO - Started process (PID=3252) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:36:18.654+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:36:18.659+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:36:18.658+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:36:19.293+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:36:19.284+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:36:19.295+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:36:19.330+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.683 seconds
[2025-09-19T04:36:49.555+0000] {processor.py:161} INFO - Started process (PID=3309) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:36:49.559+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:36:49.566+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:36:49.565+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:36:50.124+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:36:50.118+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:36:50.126+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:36:50.157+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.610 seconds
[2025-09-19T04:37:20.463+0000] {processor.py:161} INFO - Started process (PID=3366) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:37:20.465+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:37:20.468+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:37:20.468+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:37:21.025+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:37:21.018+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:37:21.028+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:37:21.058+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.602 seconds
[2025-09-19T04:37:51.154+0000] {processor.py:161} INFO - Started process (PID=3422) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:37:51.156+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:37:51.159+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:37:51.159+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:37:51.670+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:37:51.663+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:37:51.672+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:37:51.709+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.561 seconds
[2025-09-19T04:38:22.635+0000] {processor.py:161} INFO - Started process (PID=3478) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:38:22.637+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:38:22.642+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:38:22.641+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:38:23.150+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:38:23.144+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:38:23.152+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:38:23.184+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.556 seconds
[2025-09-19T04:38:53.268+0000] {processor.py:161} INFO - Started process (PID=3535) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:38:53.271+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:38:53.276+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:38:53.275+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:38:53.848+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:38:53.841+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:38:53.851+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:38:53.884+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.627 seconds
[2025-09-19T04:39:24.236+0000] {processor.py:161} INFO - Started process (PID=3592) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:39:24.238+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:39:24.242+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:39:24.241+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:39:24.777+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:39:24.770+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:39:24.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:39:24.817+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.588 seconds
[2025-09-19T04:39:55.603+0000] {processor.py:161} INFO - Started process (PID=3655) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:39:55.606+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:39:55.612+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:39:55.611+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:39:56.156+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:39:56.149+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:39:56.159+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:39:56.196+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.603 seconds
[2025-09-19T04:40:26.272+0000] {processor.py:161} INFO - Started process (PID=3713) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:40:26.274+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:40:26.277+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:40:26.277+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:40:26.778+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:40:26.771+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:40:26.781+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:40:26.818+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.551 seconds
[2025-09-19T04:40:57.681+0000] {processor.py:161} INFO - Started process (PID=3769) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:40:57.683+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:40:57.686+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:40:57.686+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:40:58.191+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:40:58.184+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:40:58.194+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:40:58.230+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.558 seconds
[2025-09-19T04:41:29.142+0000] {processor.py:161} INFO - Started process (PID=3826) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:41:29.144+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:41:29.148+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:41:29.148+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:41:29.752+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:41:29.745+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:41:29.754+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:41:29.794+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.662 seconds
[2025-09-19T04:41:59.891+0000] {processor.py:161} INFO - Started process (PID=3883) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:41:59.893+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:41:59.897+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:41:59.896+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:42:00.515+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:42:00.508+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:42:00.518+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:42:00.562+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.677 seconds
[2025-09-19T04:42:31.543+0000] {processor.py:161} INFO - Started process (PID=3940) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:42:31.546+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:42:31.549+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:42:31.549+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:42:32.090+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:42:32.083+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:42:32.092+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:42:32.126+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.590 seconds
[2025-09-19T04:43:02.269+0000] {processor.py:161} INFO - Started process (PID=3997) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:43:02.271+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:43:02.275+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:43:02.274+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:43:02.809+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:43:02.800+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:43:02.811+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:43:02.842+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.580 seconds
[2025-09-19T04:43:33.128+0000] {processor.py:161} INFO - Started process (PID=4054) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:43:33.130+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:43:33.134+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:43:33.133+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:43:33.766+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:43:33.758+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:43:33.768+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:43:33.805+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.683 seconds
[2025-09-19T04:44:04.082+0000] {processor.py:161} INFO - Started process (PID=4111) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:44:04.084+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:44:04.087+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:44:04.087+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:44:04.620+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:44:04.613+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:44:04.623+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:44:04.655+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.581 seconds
[2025-09-19T04:44:34.809+0000] {processor.py:161} INFO - Started process (PID=4170) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:44:34.811+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:44:34.815+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:44:34.814+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:44:35.519+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:44:35.513+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:44:35.521+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:44:35.558+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.756 seconds
[2025-09-19T04:45:05.716+0000] {processor.py:161} INFO - Started process (PID=4228) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:45:05.717+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:45:05.721+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:45:05.721+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:45:06.287+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:45:06.280+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:45:06.289+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:45:06.323+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.615 seconds
[2025-09-19T04:45:36.396+0000] {processor.py:161} INFO - Started process (PID=4287) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:45:36.398+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:45:36.401+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:45:36.401+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:45:36.965+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:45:36.959+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:45:36.968+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:45:37.003+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.613 seconds
[2025-09-19T04:46:07.334+0000] {processor.py:161} INFO - Started process (PID=4345) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:46:07.336+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:46:07.340+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:46:07.339+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:46:07.875+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:46:07.868+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:46:07.876+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:46:07.912+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.584 seconds
[2025-09-19T04:46:38.208+0000] {processor.py:161} INFO - Started process (PID=4402) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:46:38.209+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:46:38.214+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:46:38.213+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:46:38.719+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:46:38.710+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:46:38.721+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:46:38.758+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.557 seconds
[2025-09-19T04:47:08.896+0000] {processor.py:161} INFO - Started process (PID=4460) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:47:08.898+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:47:08.901+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:47:08.901+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:47:09.439+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:47:09.432+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:47:09.441+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:47:09.481+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.591 seconds
[2025-09-19T04:47:40.324+0000] {processor.py:161} INFO - Started process (PID=4517) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:47:40.326+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:47:40.329+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:47:40.328+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:47:40.907+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:47:40.900+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:47:40.910+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:47:40.946+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.629 seconds
[2025-09-19T04:48:11.032+0000] {processor.py:161} INFO - Started process (PID=4574) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:48:11.034+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:48:11.038+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:48:11.037+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:48:11.593+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:48:11.587+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:48:11.596+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:48:11.625+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.599 seconds
[2025-09-19T04:48:41.758+0000] {processor.py:161} INFO - Started process (PID=4633) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:48:41.759+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:48:41.763+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:48:41.762+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:48:42.249+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:48:42.241+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:48:42.252+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:48:42.288+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.537 seconds
[2025-09-19T04:49:13.009+0000] {processor.py:161} INFO - Started process (PID=4690) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:49:13.012+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:49:13.016+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:49:13.016+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:49:13.573+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:49:13.566+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:49:13.576+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:49:13.609+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.610 seconds
[2025-09-19T04:49:44.006+0000] {processor.py:161} INFO - Started process (PID=4747) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:49:44.008+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:49:44.012+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:49:44.012+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:49:44.559+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:49:44.553+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:49:44.561+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:49:44.597+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.599 seconds
[2025-09-19T04:50:14.750+0000] {processor.py:161} INFO - Started process (PID=4806) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:50:14.752+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:50:14.755+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:50:14.754+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:50:15.424+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:50:15.419+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:50:15.426+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:50:15.464+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.720 seconds
[2025-09-19T04:50:45.724+0000] {processor.py:161} INFO - Started process (PID=4865) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:50:45.726+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:50:45.731+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:50:45.730+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:50:46.444+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:50:46.437+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:50:46.446+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:50:46.487+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.772 seconds
[2025-09-19T04:51:17.028+0000] {processor.py:161} INFO - Started process (PID=4923) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:51:17.030+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:51:17.033+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:51:17.033+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:51:17.599+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:51:17.593+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:51:17.601+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:51:17.634+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.612 seconds
[2025-09-19T04:51:47.901+0000] {processor.py:161} INFO - Started process (PID=4980) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:51:47.903+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:51:47.907+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:51:47.906+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:51:48.409+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:51:48.401+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:51:48.411+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:51:48.447+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.552 seconds
[2025-09-19T04:52:18.556+0000] {processor.py:161} INFO - Started process (PID=5037) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:52:18.558+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:52:18.562+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:52:18.561+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:52:19.107+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:52:19.101+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:52:19.109+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:52:19.144+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.593 seconds
[2025-09-19T04:52:49.299+0000] {processor.py:161} INFO - Started process (PID=5096) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:52:49.301+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:52:49.304+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:52:49.303+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:52:49.776+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:52:49.768+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:52:49.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:52:49.815+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.522 seconds
[2025-09-19T04:53:20.454+0000] {processor.py:161} INFO - Started process (PID=5153) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:53:20.456+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:53:20.459+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:53:20.459+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:53:20.985+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:53:20.977+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:53:20.988+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:53:21.019+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.571 seconds
[2025-09-19T04:53:51.446+0000] {processor.py:161} INFO - Started process (PID=5210) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:53:51.448+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:53:51.451+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:53:51.451+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:53:51.986+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:53:51.978+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:53:51.988+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:53:52.024+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.584 seconds
[2025-09-19T04:54:22.598+0000] {processor.py:161} INFO - Started process (PID=5268) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:54:22.600+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:54:22.604+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:54:22.603+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:54:23.135+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:54:23.129+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:54:23.141+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:54:23.185+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.594 seconds
[2025-09-19T04:54:53.512+0000] {processor.py:161} INFO - Started process (PID=5324) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:54:53.514+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:54:53.519+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:54:53.518+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:54:54.056+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:54:54.049+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/crypto_data_generator_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_data_generator_dag.py", line 6, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-19T04:54:54.059+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:54:54.093+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.588 seconds
[2025-09-19T04:57:46.394+0000] {processor.py:161} INFO - Started process (PID=68) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:57:46.410+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:57:46.435+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:57:46.434+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:57:52.292+0000] {processor.py:840} INFO - DAG(s) 'crypto_data_generator' retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:57:52.671+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:57:52.670+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:crypto_data_generator
[2025-09-19T04:57:52.697+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:57:52.696+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:crypto_data_generator
[2025-09-19T04:57:52.714+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:57:52.714+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:crypto_data_generator
[2025-09-19T04:57:52.716+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:57:52.715+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-09-19T04:57:52.745+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:57:52.744+0000] {dag.py:3058} INFO - Creating ORM DAG for crypto_data_generator
[2025-09-19T04:57:52.794+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:57:52.793+0000] {dag.py:3823} INFO - Setting next_dagrun for crypto_data_generator to 2025-09-19 03:00:00+00:00, run_after=2025-09-19 04:00:00+00:00
[2025-09-19T04:57:52.900+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 6.562 seconds
[2025-09-19T04:58:23.113+0000] {processor.py:161} INFO - Started process (PID=131) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:58:23.116+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:58:23.120+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:58:23.120+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:58:24.041+0000] {processor.py:840} INFO - DAG(s) 'crypto_data_generator' retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:58:24.087+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:58:24.087+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-09-19T04:58:24.126+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:58:24.126+0000] {dag.py:3823} INFO - Setting next_dagrun for crypto_data_generator to 2025-09-19 03:00:00+00:00, run_after=2025-09-19 04:00:00+00:00
[2025-09-19T04:58:24.158+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 1.052 seconds
[2025-09-19T04:58:54.454+0000] {processor.py:161} INFO - Started process (PID=188) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:58:54.458+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:58:54.464+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:58:54.463+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:58:57.271+0000] {processor.py:840} INFO - DAG(s) 'crypto_data_generator' retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:58:57.323+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:58:57.322+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-09-19T04:58:57.370+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:58:57.370+0000] {dag.py:3823} INFO - Setting next_dagrun for crypto_data_generator to 2025-09-19 03:00:00+00:00, run_after=2025-09-19 04:00:00+00:00
[2025-09-19T04:58:57.406+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 2.961 seconds
[2025-09-19T04:59:27.879+0000] {processor.py:161} INFO - Started process (PID=250) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:59:27.881+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T04:59:27.888+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:59:27.887+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:59:32.588+0000] {processor.py:840} INFO - DAG(s) 'crypto_data_generator' retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T04:59:32.624+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:59:32.623+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-09-19T04:59:32.677+0000] {logging_mixin.py:188} INFO - [2025-09-19T04:59:32.677+0000] {dag.py:3823} INFO - Setting next_dagrun for crypto_data_generator to 2025-09-19 03:00:00+00:00, run_after=2025-09-19 04:00:00+00:00
[2025-09-19T04:59:32.712+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 4.841 seconds
[2025-09-19T05:00:02.811+0000] {processor.py:161} INFO - Started process (PID=314) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T05:00:02.813+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T05:00:02.818+0000] {logging_mixin.py:188} INFO - [2025-09-19T05:00:02.817+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T05:00:04.505+0000] {processor.py:840} INFO - DAG(s) 'crypto_data_generator' retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T05:00:04.550+0000] {logging_mixin.py:188} INFO - [2025-09-19T05:00:04.548+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-09-19T05:00:04.609+0000] {logging_mixin.py:188} INFO - [2025-09-19T05:00:04.609+0000] {dag.py:3823} INFO - Setting next_dagrun for crypto_data_generator to 2025-09-19 04:00:00+00:00, run_after=2025-09-19 05:00:00+00:00
[2025-09-19T05:00:04.661+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 1.867 seconds
[2025-09-19T05:00:34.998+0000] {processor.py:161} INFO - Started process (PID=372) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T05:00:35.000+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T05:00:35.004+0000] {logging_mixin.py:188} INFO - [2025-09-19T05:00:35.003+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T05:00:35.927+0000] {processor.py:840} INFO - DAG(s) 'crypto_data_generator' retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T05:00:35.957+0000] {logging_mixin.py:188} INFO - [2025-09-19T05:00:35.956+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-09-19T05:00:35.998+0000] {logging_mixin.py:188} INFO - [2025-09-19T05:00:35.997+0000] {dag.py:3823} INFO - Setting next_dagrun for crypto_data_generator to 2025-09-19 04:00:00+00:00, run_after=2025-09-19 05:00:00+00:00
[2025-09-19T05:00:36.036+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 1.046 seconds
[2025-09-19T05:01:06.123+0000] {processor.py:161} INFO - Started process (PID=433) to work on /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T05:01:06.125+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_data_generator_dag.py for tasks to queue
[2025-09-19T05:01:06.129+0000] {logging_mixin.py:188} INFO - [2025-09-19T05:01:06.128+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T05:01:06.956+0000] {processor.py:840} INFO - DAG(s) 'crypto_data_generator' retrieved from /opt/airflow/dags/crypto_data_generator_dag.py
[2025-09-19T05:01:06.983+0000] {logging_mixin.py:188} INFO - [2025-09-19T05:01:06.982+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-09-19T05:01:07.020+0000] {logging_mixin.py:188} INFO - [2025-09-19T05:01:07.019+0000] {dag.py:3823} INFO - Setting next_dagrun for crypto_data_generator to 2025-09-19 04:00:00+00:00, run_after=2025-09-19 05:00:00+00:00
[2025-09-19T05:01:07.058+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_data_generator_dag.py took 0.941 seconds
